FROM alpine:edge

RUN apk add --update g++ m4 libtool make upx curl xz libarchive perl sed file \
    curl-dev libarchive-dev libressl-dev xz-dev zlib-dev bzip2-dev libssh2-dev acl-dev lz4-dev expat-dev linux-headers \
  && rm -rf /var/cache/apk/*
